### ISSUE TITLE
Error on get-device-info to P110

### ISSUE THREAD

**Issue by marshallartsoz** [ClementNerma/tapo-rest#13]
I've been using this to monitor energy usage from several P110 smart plugs, works beautifully.  My mind has now turned to being able to switch them on/off, and checking their on/off state.  I tried sending a **get-device-info** action to one of them, thinking the response body might include on/off state.  But I get a statusCode of 500 returned, with the message "Serde: missing field `overheated` at line 1 column 817".  A bug?  Whether it is or not, it might be nice to have a simpler query action to return just the on/off state of the device, rather than full device info.  It would be applicable to most of the supported device types I would think.  Maybe like ..../actions/devtype/state?device=xxxxxx.  But if get-device-info worked, that would be fine. :-)

**Comment by ClementNerma** [comment]
This is an issue with the underlying `tapo` library, you can open an issue here: https://github.com/mihai-dinculescu/tapo/issues

Also, querying the entire device's info is basically instant, it's only one request to the device, and a way to ensure the device is responding correctly - otherwise it may indicate a bug with the library. Hence why there is no 'on/off' fetching route :)

**Comment by marshallartsoz** [comment]
I'm as sure as I can be that the issue has been fixed in that project, just a few weeks ago.  I downloaded it and ran the one of the samples, and the error does not occur. Do you rebuild your precompiled binaries every now and then, to take up these dependency upgrades?  That would be very helpful.

**Comment by ClementNerma** [comment]
I bundle the latest published `tapo` version. At the time you opened this issue, the fix wasn't put in a release yet.

I've just published a new version of `tapo-rest` with the new `tapo` version, this should normally solve the issue :)

**Comment by marshallartsoz** [comment]
Love your work!  :-D

Yes the device-info query is now fine.  Issue resolved.  Merci mille fois.
