### ISSUE TITLE
SessionTimeout after some time

### ISSUE THREAD

**Issue by hanibalsk** [ClementNerma/tapo-rest#15]
Nice server, only think, I found, is SessionTimeout. Server needs to be restarted manually to login again

I created docker image build script for Docker [Docker build script](https://github.com/hanibalsk/tapo-rest-crossplatform)

**Comment by ClementNerma** [comment]
Hi,

Could you explain what problem exactly you're having? In which case is a timeout happening, and what is the exact error message you're getting?

Thanks.

**Comment by hanibalsk** [comment]
For instance on Fri, 15 Nov 2024 09:25:39 GMT when server is running just for a while it has session of bulb connected

```
(.venv) MacBook-Pro tapo-rest % curl -i -X GET -H 'Authorization: Bearer mBDukqC4MFF8f5Pu3ypj1mXNGtXMkqg' 'http://tapo.xxx.sk/actions/l530/off?device=living-room-bulb'
HTTP/1.1 200 OK
Server: nginx
Date: Fri, 15 Nov 2024 09:25:39 GMT
Content-Length: 0
Connection: keep-alive
Keep-Alive: timeout=20
vary: origin, access-control-request-method, access-control-request-headers
access-control-allow-origin: *
```
I think on the bulb is session limited for some period, so when there is request going thru tapo-rest, session is not renewed
```
(.venv) MacBook-Pro tapo-rest % curl -i -X GET -H 'Authorization: Bearer mBDukqC4MFF8f5Pu3ypj1mXNGtXMkqg' 'http://tapo.xxx.sk/actions/l530/off?device=living-room-bulb'
HTTP/1.1 500 Internal Server Error
Server: nginx
Date: Fri, 15 Nov 2024 15:40:37 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 20
Connection: keep-alive
Keep-Alive: timeout=20
vary: origin, access-control-request-method, access-control-request-headers
access-control-allow-origin: *

Tapo: SessionTimeout%   
```

Device info:
```
  "type": "SMART.TAPOBULB",
  "model": "L535",
  "hw_id": "75A579FB67A2FFBEB6DB027CCBE46D1D",
  "hw_ver": "3.0",
  "fw_id": "00000000000000000000000000000000",
  "fw_ver": "1.1.5 Build 240328 Rel.194528",
  "oem_id": "CC252911A40F78C37397C8661697465F",
```

Of course, after restart, server will login again and it is working fine again. Looks like problem is server -> bulb not client -> server

**Comment by ClementNerma** [comment]
Hi, sorry for the late reply.

I've implemented a mechanism to refresh the session manually: you can now hit the `/refresh-session?device...` route.

You'll need to do this manually though as there is no mechanism to detect automatically when a session has expired.
