### ISSUE TITLE
[FEAT]: Container image

### ISSUE THREAD

**Issue by KillerJulian** [ClementNerma/tapo-rest#17]
Can you provide a container image for arm64 and similar architectures in the Docker Hub?

**Comment by ClementNerma** [comment]
I could but I don't think that's very useful given you can already [download the prebuilt binaries](https://github.com/ClementNerma/tapo-rest/releases/latest). You can just run them, they don't have any system dependency (openssl is bundled in the binary).

Is there a specific use case where you wouldn't be able to just run the binary by itself?

**Comment by ClementNerma** [comment]
Seems reasonable.

I've added a `Dockerfile` to the project, I'll try to publish it later.

You can try it on your machine by running:

```shell
# Clone the repository
git clone https://github.com/ClementNerma/tapo-rest

# Build a Docker image
docker build -t tapo-rest .

# Start the container
docker run -it -v ./path-to-my-config.json:/app/devices.json tapo-rest --port 8000 --auth-password 'yoh'
```

Tell me if it works on your side :)

**Comment by KillerJulian** [comment]
> Tell me if it works on your side :)
LGTM for `linux/amd64`

Thank you for your very quick response. I have a GitHub workflow that we can add to this project if you want to automate the building and publishing of Docker images

**Comment by KillerJulian** [comment]
Does it make sense to make the username and password available as ENV? That way there is no risk of sharing the json. I plan to add further information in the `devices.json`, which will then be accessed by another process

**Comment by KillerJulian** [comment]
A small note that there is now a Docker image available would also make sense in the README. Some users would be pleased about this.

Thank you for your work!

**Comment by ClementNerma** [comment]
I could move the username and password to command-line flags, and make them fallback to environment variables if not provided (just like the authentication password).

I'll try to do that when I have time, this will be a breaking change so it'll be a new `0.2.0` version.

And yes I will mention the Docker image in the README, as soon as I get it working (the container works but I can't for the sake of me publish it successfully).

**Comment by ClementNerma** [comment]
You know what? I have time and motivation right now! So it's done: https://github.com/ClementNerma/tapo-rest/releases/tag/v0.2.0

```shell
TAPO_EMAIL='...' TAPO_PASSWORD='...' PORT='...' AUTH_PASSWORD='...' tapo-rest ./config.json
```

Enjoy :)

**Comment by ClementNerma** [comment]
FYI there's now a published docker image under the name of `clementnerma/tapo-rest` ;)
