### ISSUE TITLE
Connecting devices

### ISSUE THREAD

**Issue by tuliuliucroman** [ClementNerma/tapo-rest#2]
Good afternoon. I ask for help. I installed the app. Everything started up fine. But I can't figure out how to add TAPO devices to Home Assistant. Please help me with more detailed instructions.

**Comment by ClementNerma** [comment]
Hi, this project is only designed to provide a REST API for Tapo devices. It is not designed specifically for Home Assistant.

I believe what you want is something like this: https://github.com/JurajNyiri/HomeAssistant-Tapo-Control
