### ISSUE TITLE
Implement get_current_power for P110

### ISSUE THREAD

**Issue by Budgiebrain994** [ClementNerma/tapo-rest#7]
Hi

Upstream, a new data value is available:

https://github.com/mihai-dinculescu/tapo/blob/4ad1107c61c237534a2bea8ddd2da99d9993235f/tapo/src/api/api_client.rs#L596

Please consider implementing this as an endpoint.

Thank you!

**Comment by ClementNerma** [comment]
Will do in the evening if I got time.
Thanks for reporting!

**Comment by ClementNerma** [comment]
This should now work on the [latest release](https://github.com/ClementNerma/tapo-rest/releases/tag/v0.1.1) ;)

**Comment by Budgiebrain994** [comment]
Absolute legend! Thank you.
