### ISSUE TITLE
I integrated this with Cinnamon applets

### ISSUE THREAD

**Issue by smiklosovic** [ClementNerma/tapo-rest#8]
Hello @ClementNerma 

I just want to say: great job!

I integrated this with (1), it is a small applet I wrote for Linux Mint / Cinnamon so I can control my plugs from a task bar :).

(1) https://github.com/linuxmint/cinnamon-spices-applets/pull/6346

**Comment by smiklosovic** [comment]
https://cinnamon-spices.linuxmint.com/applets/view/398

**Comment by ClementNerma** [comment]
Hi, thanks for your work :)

I'll mention it in the README when I commit again in the repo in the next few days :)

**Comment by ClementNerma** [comment]
Totally forgot to add it to the README, just done it right now ^^
